#!/bin/sh

# Git repos
# git clone git@github.com:Stargazer3240/scripts.git ~/.scripts/
# git clone git@github.com:Stargazer3240/dotfiles.git ~/.dotfiles/

# DNF
sudo dnf install stow alacritty zsh bat lsd neovim python3-neovim nodejs fd-find ripgrep python3-pip snapd just libreoffice-langpack-pt-BR -y
sudo dnf group install "Ferramentas de Desenvolvimento C e Bibliotecas" -y
sudo dnf remove mediawriter -y
cp /usr/share/applications/nvim.desktop .local/share/applications/
echo Hidden=true >> .local/share/applications/nvim.desktop

# Dotfiles
cd ~/.dotfiles || exit
stow zsh alacritty git

# Audio volume
amixer set Master 50%
amixer set Capture 35%
