#!/bin/sh

# Git repos
# git clone git@github.com:Stargazer3240/scripts.git ~/.scripts/
# git clone git@github.com:Stargazer3240/dotfiles.git ~/.dotfiles/

# DNF
sudo dnf install stow alacritty zsh bat lsd neovim python3-neovim nodejs fd-find ripgrep python3-pip snapd just mangohud -y
sudo dnf group install "Ferramentas de Desenvolvimento C e Bibliotecas" -y
sudo dnf remove "libreoffice*" -y
sudo dnf group remove LibreOffice -y

# Dotfiles
cd ~/.dotfiles || exit
stow zsh alacritty git
sudo lchsh fabricio

# Audio volume
amixer set Master 50%
amixer set Capture 35%
