#!/bin/sh

# Git repos
git clone git@github.com:Stargazer3240/scripts.git ~/.scripts/
git clone git@github.com:Stargazer3240/dotfiles.git ~/.dotfiles/

# DNF
sudo dnf install stow alacritty zsh bat lsd neovim python3-neovim steam-devices nodejs fd-find ripgrep -y
sudo dnf group install "Ferramentas de Desenvolvimento C e Bibliotecas"
sudo dnf remove firefox "libreoffice*" -y
sudo dnf group remove LibreOffice -y

# Gnome
sudo dnf install gnome-tweaks f36-backgrounds-gnome gnome-shell-extension-no-overview gnome-shell-extension-appindicator -y
sudo dnf remove gnome-maps gnome-logs gnome-font-viewer gnome-photos gnome-tour gnome-weather gnome-calendar gnome-characters gnome-clocks gnome-contacts totem cheese simple-scan gnome-abrt rhythmbox gnome-connections -y
gsettings set org.gnome.mutter check-alive-timeout 60000

# zram
echo "[zram0]
zram-size = ram * 2
compression-algorithm = zstd" | sudo tee /usr/lib/systemd/zram-generator.conf
sudo systemctl daemon-reload
sudo systemctl restart systemd-zram-setup@zram0.service

# Dotfiles
cd ~/.dotfiles || exit
stow zsh alacritty git nvim
sudo lchsh fabricio
