#!/bin/sh

flatpak install \
  org.gimp.GIMP \
  it.mijorus.gearlever \
  com.github.tchx84.Flatseal \
  io.freetubeapp.FreeTube \
  org.freedesktop.Platform.ffmpeg-full \
  com.borgbase.Vorta \
  com.calibre_ebook.calibre \
  org.libreoffice.LibreOffice \
  -y
