#!/bin/sh
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
. "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
git clone git@github.com:Stargazer3240/home-manager.git ~/.config/home-manager/
nix run home-manager/master -- init --switch
. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
home-manager switch
