#!/bin/sh

sudo dnf update -y
sudo dnf install akmod-nvidia -y
sudo dnf install xorg-x11-drv-nvidia-cuda -y
sudo dnf mark user akmod-nvidia -y
sudo grubby --update-kernel=ALL --args='nvidia-drm.modeset=1'
sudo dnf install xorg-x11-drv-nvidia-cuda-libs -y
sudo dnf install nvidia-vaapi-driver libva-utils vdpauinfo -y
