#!/bin/sh
git clone git@github.com:Stargazer3240/scripts.git ~/.scripts/
git clone git@github.com:Stargazer3240/home-manager.git ~/.config/home-manager/
git clone git@github.com:Stargazer3240/dotfiles.git ~/.dotfiles/
gir clone git@github.com:Stargazer3240/lazyvim-config.git ~/.config/nvim/
