#!/bin/sh
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1) -y
flatpak remote-delete fedora
flatpak uninstall --unused --delete-data -y
flatpak install \
	org.mozilla.firefox \
	org.libreoffice.LibreOffice \
	org.gimp.GIMP \
	it.mijorus.gearlever \
	io.github.celluloid_player.Celluloid \
	com.valvesoftware.Steam \
	com.github.tchx84.Flatseal \
	com.github.Eloston.UngoogledChromium \
	com.github.wwmm.easyeffects \
  org.gnome.World.PikaBackup \
	-y
